# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: MyLocalAgents

stages:

# -----------------
# CI STAGE
# -----------------
- stage: Build
  jobs:
  - job: BuildVue
    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: Install Node

    - script: |
        cd $(Build.SourcesDirectory)
        npm install
        npm run build
      displayName: Build Vue App

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)/dist'
        artifact: 'vue-dist'

# -----------------
# CD STAGE
# -----------------
- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployToAzure
    steps:

    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'vue-dist'
        path: '$(Build.ArtifactStagingDirectory)/vue-dist'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'azure-connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az storage blob upload-batch \
            --account-name wepapp19 \
            --destination '$web' \
            --source $(Build.ArtifactStagingDirectory)/vue-dist
